<?php

use Fisharebest\Webtrees\Auth;
use Fisharebest\Webtrees\Date;
use Fisharebest\Webtrees\Elements\UnknownElement;
use Fisharebest\Webtrees\Fact;
use Fisharebest\Webtrees\Family;
use Fisharebest\Webtrees\Gedcom;
use Fisharebest\Webtrees\GedcomRecord;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Module\ModuleChartInterface;
use Fisharebest\Webtrees\Module\ModuleInterface;
use Fisharebest\Webtrees\Module\RelationshipsChartModule;
use Fisharebest\Webtrees\Registry;
use Fisharebest\Webtrees\Services\ModuleService;
use Fisharebest\Webtrees\Services\RelationshipService;
use Fisharebest\Webtrees\Tree;
use Ramsey\Uuid\Uuid;

/**
 * @var Fact   $fact
 * @var string $id
 */

$tree   = $fact->record()->tree();
$record = $fact->record();

// Does this fact have an explicit DATE tag?
$date = $fact->date();

// Get the tag for this fact
$tag = $fact->tag();

// Get the value of this fact
$value = $fact->value();

// Get the type of this fact
$type = $fact->attribute('TYPE');

// Create a unique identifier for this fact
$id = $id ?? 'fact-' . Uuid::uuid4()->toString();

// Get an element object for this fact
$element = Registry::elementFactory()->make($fact->tag());

// What record are we displaying this fact on?
$record_tag = $record->tag();

// Get a label for this fact
if ($tag === 'EVEN' || $tag === 'FACT') {
    $label = $element->label();
    if ($type !== '') {
        $label = I18N::translate($type);
    } elseif ($value !== '') {
        $label = $value;
    }
} else {
    $label = $element->label();
}

// If this fact is from a parent family, get that family
$parent = null;
$associates = $fact->attribute('ASSO');
if ($associates !== '') {
    $parent = Registry::familyFactory()->make($associates, $tree) ?? Registry::individualFactory()->make($associates, $tree);
}

// If this is a death fact, see if there is an AGE tag
$age = '';
if ($tag === 'DEAT' && $record instanceof Individual) {
    foreach ($fact->attributes() as $key => $val) {
        if ($key === 'AGE') {
            $age = $val;
            break;
        }
    }
}

?>

<tr class="<?= $fact->isPendingAddition() ? 'wt-new' : '' ?> <?= $fact->isPendingDeletion() ? 'wt-old' : '' ?>" id="<?= e($id) ?>">
    <th scope="row" class="wt-fact-label">
        <?= $label ?>
        
        <?php if ($tree->getPreference('SHOW_FACT_ICONS') === '1') : ?>
            <?php
            // Sex icons using Font Awesome
            if ($tag === 'SEX') {
                if ($value === 'M') {
                    echo '<i class="fas fa-mars wt-sex-m" title="' . I18N::translate('Male') . '"></i>';
                } elseif ($value === 'F') {
                    echo '<i class="fas fa-venus wt-sex-f" title="' . I18N::translate('Female') . '"></i>';
                } elseif ($value === 'U') {
                    echo '<i class="fas fa-genderless wt-sex-u" title="' . I18N::translate('Unknown') . '"></i>';
                } elseif ($value === 'X') {
                    echo '<i class="fas fa-transgender wt-sex-x" title="' . I18N::translate('Other') . '"></i>';
                }
            }
            ?>
        <?php endif ?>

        <?= view('fact-edit-links', ['fact' => $fact, 'url' => $record->url()]) ?>
    </th>

    <td class="wt-fact-value">
        <?php if ($tag === 'NOTE' || $tag === 'SHARED_NOTE') : ?>
            <?php foreach ($fact->target()->facts(['NOTE']) as $note) : ?>
                <?= view('fact-gedcom-fields', ['gedcom' => $note->gedcom(), 'parent' => $fact->target()->tag(), 'tree' => $fact->record()->tree()]) ?>
            <?php endforeach ?>
        <?php else : ?>
            <div class="wt-fact-main-attributes">
                <?php if ($parent !== null) : ?>
                    <div class="wt-fact-record">
                        <?php if ($parent instanceof Family) : ?>
                            <?php foreach ($parent->spouses()->filter(static fn ($individual): bool => $individual !== $record) as $spouse) : ?>
                                <div>
                                <?php if ($spouse->tree()->getPreference('SHOW_HIGHLIGHT_IMAGES')) : ?>
                                    <div class="wt-chart-box-thumbnail float-start me-1">
                                        <?= $spouse->displayImage(40, 50, 'crop', ['class' => 'wt-chart-box-thumbnail']) ?>
                                    </div>
                                <?php endif ?>                                  
                                <a href="<?= e($spouse->url()) ?>"><?= $spouse->fullName() ?></a> —
                                </div>
                            <?php endforeach ?>
                            <a href="<?= e($parent->url()) ?>"><?= I18N::translate('View this family') ?></a>
                        <?php elseif ($parent instanceof Individual) : ?>
                            <div class=thumbnail_container>
                            <?php if ($parent->tree()->getPreference('SHOW_HIGHLIGHT_IMAGES')) : ?>
                                <div class="wt-chart-box-thumbnail float-start me-1">
                                    <?= $parent->displayImage(40, 50, 'crop', ['class' => 'wt-chart-box-thumbnail']) ?>
                                </div>
                            <?php endif ?>                              
                            <a href="<?= e($parent->url()) ?>"><?= $parent->fullName() ?></a>
                            </div>
                        <?php endif ?>
                    </div>
                <?php endif ?>

                <div class="wt-fact-value">
                    <?= $element->value($value, $tree) ?>
                    <?php if ($element instanceof XrefAssociate && $fact->target() instanceof Individual) : ?>
                        <?php
                        $module = Registry::container()->get(ModuleService::class)->findByComponent(ModuleChartInterface::class, $tree, Auth::user())
                            ->first(static fn (ModuleInterface $module): bool => $module instanceof RelationshipsChartModule)
                        ?>

                        <?php if ($module instanceof RelationshipsChartModule && $record instanceof Individual) : ?>                             
                            — <a href="<?= $module->chartUrl($fact->target(), ['xref2' => $record->xref()]) ?>" rel="nofollow">
                                <?= Registry::container()->get(RelationshipService::class)->getCloseRelationshipName($record, $fact->target()) ?>
                            </a>
                        <?php endif ?>
                    <?php endif ?>
                </div>

                <!-- Type of this fact/event (allow user-translations) -->
                <?php if ($type !== '' && $tag !== 'EVEN' && $tag !== 'FACT') : ?>
                    <div class="wt-fact-type">
                        <?= Registry::elementFactory()->make($fact->tag() . ':TYPE')->labelValue(I18N::translate($type), $tree) ?>
                    </div>
                <?php endif ?>

                <?= view('fact-date', ['cal_link' => 'true', 'fact' => $fact, 'record' => $record, 'time' => true]) ?>
                <?= view('fact-place', ['fact' => $fact, 'record' => $record]) ?>
            </div>

            <div class="wt-fact-other-attributes mt-2">
                <?php preg_match_all('/\n2 (' . Gedcom::REGEX_TAG . ')( .*)?((\n[3-9].*)*)/', $fact->gedcom(), $matches, PREG_SET_ORDER) ?>
                <?php foreach ($matches as $match) : ?>
                    <?php if (!in_array($match[1], ['DATE', 'AGE', 'HUSB', 'WIFE', 'PLAC', 'ASSO', '_ASSO', 'STAT', 'TEMP', 'TYPE', 'CONT', 'NOTE', 'OBJE', 'SOUR'], true)) : ?>
                        <?= view('fact-gedcom-fields', ['gedcom' => $match[0], 'parent' => $fact->tag() . ':' . $match[1], 'tree' => $tree]) ?>
                    <?php endif ?>
                <?php endforeach; ?>
            </div>

            <?php if ($id !== 'asso') : ?>
                <?= view('fact-associates', ['fact' => $fact]) ?>
            <?php endif ?>

            <?= view('fact-sources', ['fact' => $fact]) ?>
            <?= view('fact-notes', ['fact' => $fact]) ?>
            <?= view('fact-media', ['fact' => $fact]) ?>
        <?php endif ?>
    </td>
</tr>
