<?php

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Media;
use Fisharebest\Webtrees\Tree;
use Illuminate\Support\Collection;

/**
 * @var bool                   $can_upload_media
 * @var Collection<int,Media>  $individual_media
 * @var Individual             $record
 * @var Tree                   $tree
 */

?>

<?php if ($individual_media->isEmpty()) : ?>
    <div class="wt-individual-silhouette wt-individual-silhouette-<?= strtolower($record->sex()) ?>"></div>
<?php elseif ($individual_media->count() === 1) : ?>
    <?= $individual_media->first()->displayImage(150, 150, 'crop', ['class' => 'wt-individual-silhouette wt-individual-silhouette-' . strtolower($record->sex())]) ?>
<?php else : ?>
    <div id="individual-images-<?= e($record->xref()) ?>" class="carousel slide" data-ride="carousel" data-interval="false">
        <div class="carousel-indicators">
            <?php foreach ($individual_media as $n => $media_file) : ?>
                <button type="button" data-slide-target="#individual-images-<?= e($record->xref()) ?>" data-slide-to="<?= $n ?>" <?= $n === 0 ? 'class="active"' : '' ?>></button>
            <?php endforeach ?>
        </div>
        <div class="carousel-inner">
            <?php foreach ($individual_media as $n => $media_file) : ?>
                <div class="carousel-item <?= $n === 0 ? 'active' : '' ?>">
                    <?= $media_file->displayImage(150, 150, 'crop', ['class' => 'wt-individual-silhouette wt-individual-silhouette-' . strtolower($record->sex())]) ?>
                </div>
            <?php endforeach ?>
        </div>
        <a class="carousel-control-prev" href="#individual-images-<?= e($record->xref()) ?>" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden"><?= I18N::translate('Previous') ?></span>
        </a>
        <a class="carousel-control-next" href="#individual-images-<?= e($record->xref()) ?>" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden"><?= I18N::translate('Next') ?></span>
        </a>
    </div>
<?php endif ?>
