<?php

use Fisharebest\Webtrees\Fact;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Tree;
use Illuminate\Support\Collection;

/**
 * @var Collection<string,Fact> $name_facts
 * @var Individual              $record
 * @var Tree                    $tree
 */

?>

<div class="accordion" id="individual-names">
    <?php foreach ($name_facts as $fact) : ?>
        <?= view('individual-page-name', ['fact' => $fact, 'record' => $record, 'tree' => $tree]) ?>
    <?php endforeach ?>
</div>
