<?php

use Fisharebest\Webtrees\Individual;

/**
 * @var Individual $record
 */
?>

<div class="accordion" id="individual-names">
    <?php foreach ($record->facts(['NAME']) as $fact) : ?>
        <?= view('individual-page-name', ['fact' => $fact]) ?>
    <?php endforeach ?>

    <?php foreach ($record->facts(['SEX']) as $fact) : ?>
        <?= view('individual-page-sex', ['fact' => $fact]) ?>
    <?php endforeach ?>
</div>
